In [2]:
import pandas as pd

In [170]:
kp=pd.read_csv("C:/Users/Kailash J Choudhary/Downloads/orders_raw_messy.csv")
kp_product=pd.read_csv("C:/Users/Kailash J Choudhary/Downloads/products_clean.csv")

In [171]:
kp.head()

,order_id,customer_id,product_id,order_date,ship_date,quantity,unit_price,discount_percent,shipping_cost,total_amount,payment_method,order_status,region,sales_channel,return_flag
0,ORD01073,CUST0013,PROD0086,17-03-2023,22-03-2023,1,1008.99,NaN,72.84,1081.83,Cash on Delivery,Processing,north,Mobile app,No
1,ORD01049,CUST0060,PROD0016,29-05-2023,27-05-2023,1,9295.74,0.0,146.52,9442.26,Cash on Delivery,processing,west,Mobile App,No
2,ORD00205,CUST0128,PROD0070,06-01-2023,13-01-2023,5,2262.55,5.0,54.22,10801.33,net banking,shipped,NaN,Mobile app,No
3,ORD00695,CUST0190,PROD0033,28-11-2024,07-12-2024,4,14138.95,10.0,134.07,51034.29,Debit Card,delivered,NaN,online,No
4,ORD01759,CUST0100,PROD0018,"Mar 13, 2024",19-03-2024,3,21702.52,0.0,117.80,65225.36,net banking,Returned,west,in-store,No

In [172]:
kp.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          2000 non-null   str
 1   customer_id       1997 non-null   str
 2   product_id        1997 non-null   str
 3   order_date        2000 non-null   str
 4   ship_date         1847 non-null   str
 5   quantity          2000 non-null   int64
 6   unit_price        2000 non-null   str
 7   discount_percent  1743 non-null   float64
 8   shipping_cost     1907 non-null   float64
 9   total_amount      2000 non-null   float64
 10  payment_method    1948 non-null   str
 11  order_status      2000 non-null   str
 12  region            1630 non-null   str
 13  sales_channel     2000 non-null   str
 14  return_flag       1795 non-null   str
dtypes: float64(3), int64(1), str(11)
memory usage: 401.0 KB

In [173]:
kp.isnull().sum()

order_id              0
customer_id           3
product_id            3
order_date            0
ship_date           153
quantity              0
unit_price            0
discount_percent    257
shipping_cost        93
total_amount          0
payment_method       52
order_status          0
region              370
sales_channel         0
return_flag         205
dtype: int64

In [174]:
kp["payment_method"]=kp["payment_method"].str.strip().str.title()
kp["payment_method"]=kp["payment_method"].replace("Cash On Delivery","COD")

In [175]:
kp["payment_method"].unique()

<ArrowStringArray>
['COD', 'Net Banking', 'Debit Card', 'Upi', 'Cod', 'Credit Card', nan]
Length: 7, dtype: str

In [176]:
kp["order_status"]=kp["order_status"].str.strip().str.title()

In [177]:
kp["region"]=kp["region"].str.strip().str.title()

In [178]:
kp["sales_channel"]=kp["sales_channel"].str.strip().str.title()

In [179]:
kp["return_flag"]=kp["return_flag"].str.strip().str.title()

In [180]:
print("Hello")

Hello

In [181]:
kp["order_id"].duplicated().sum()

np.int64(150)

In [182]:
kp.drop_duplicates(subset="order_id",inplace=True)

In [183]:
kp.duplicated().sum()

np.int64(0)

In [184]:
kp

,order_id,customer_id,product_id,order_date,ship_date,quantity,unit_price,discount_percent,shipping_cost,total_amount,payment_method,order_status,region,sales_channel,return_flag
0,ORD01073,CUST0013,PROD0086,17-03-2023,22-03-2023,1,1008.99,NaN,72.84,1081.83,COD,Processing,North,Mobile App,No
1,ORD01049,CUST0060,PROD0016,29-05-2023,27-05-2023,1,9295.74,0.0,146.52,9442.26,COD,Processing,West,Mobile App,No
2,ORD00205,CUST0128,PROD0070,06-01-2023,13-01-2023,5,2262.55,5.0,54.22,10801.33,Net Banking,Shipped,NaN,Mobile App,No
3,ORD00695,CUST0190,PROD0033,28-11-2024,07-12-2024,4,14138.95,10.0,134.07,51034.29,Debit Card,Delivered,NaN,Online,No
4,ORD01759,CUST0100,PROD0018,"Mar 13, 2024",19-03-2024,3,21702.52,0.0,117.80,65225.36,Net Banking,Returned,West,In-Store,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,ORD01604,CUST0087,PROD0035,27-11-2024,25-11-2024,2,13720.55,0.0,152.21,27593.31,Upi,Cancelled,NaN,Mobile App,No
1996,ORD00503,CUST0058,PROD0007,11-01-2023,11-01-2023,1,2136.66,15.0,215.35,2031.51,Net Banking,Delivered,North,Mobile App,Yes
1997,ORD00538,CUST0021,PROD0071,05-05-2024,05-05-2024,2,1509.25,0.0,26.02,3044.52,Debit Card,Delivered,North,Online,No
1998,ORD01221,CUST0156,PROD0090,01-11-2024,NaN,4,12088.33,0.0,NaN,48561.19,Upi,Delivered,NaN,Mobile App,No
1999,ORD00176,CUST0154,PROD0071,14-06-2023,13-06-2023,-1,₹1509.25,0.0,112.35,1621.60,Credit Card,Delivered,NaN,Mobile App,No

In [185]:
kp["order_date"] = pd.to_datetime(kp["order_date"],format="mixed")

In [186]:
kp["ship_date"] = pd.to_datetime(kp["ship_date"], format="mixed")
kp

,order_id,customer_id,product_id,order_date,ship_date,quantity,unit_price,discount_percent,shipping_cost,total_amount,payment_method,order_status,region,sales_channel,return_flag
0,ORD01073,CUST0013,PROD0086,2023-03-17,2023-03-22,1,1008.99,NaN,72.84,1081.83,COD,Processing,North,Mobile App,No
1,ORD01049,CUST0060,PROD0016,2023-05-29,2023-05-27,1,9295.74,0.0,146.52,9442.26,COD,Processing,West,Mobile App,No
2,ORD00205,CUST0128,PROD0070,2023-06-01,2023-01-13,5,2262.55,5.0,54.22,10801.33,Net Banking,Shipped,NaN,Mobile App,No
3,ORD00695,CUST0190,PROD0033,2024-11-28,2024-07-12,4,14138.95,10.0,134.07,51034.29,Debit Card,Delivered,NaN,Online,No
4,ORD01759,CUST0100,PROD0018,2024-03-13,2024-03-19,3,21702.52,0.0,117.80,65225.36,Net Banking,Returned,West,In-Store,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,ORD01604,CUST0087,PROD0035,2024-11-27,2024-11-25,2,13720.55,0.0,152.21,27593.31,Upi,Cancelled,NaN,Mobile App,No
1996,ORD00503,CUST0058,PROD0007,2023-11-01,2023-11-01,1,2136.66,15.0,215.35,2031.51,Net Banking,Delivered,North,Mobile App,Yes
1997,ORD00538,CUST0021,PROD0071,2024-05-05,2024-05-05,2,1509.25,0.0,26.02,3044.52,Debit Card,Delivered,North,Online,No
1998,ORD01221,CUST0156,PROD0090,2024-01-11,NaT,4,12088.33,0.0,NaN,48561.19,Upi,Delivered,NaN,Mobile App,No
1999,ORD00176,CUST0154,PROD0071,2023-06-14,2023-06-13,-1,₹1509.25,0.0,112.35,1621.60,Credit Card,Delivered,NaN,Mobile App,No

In [187]:
kp.info()

<class 'pandas.DataFrame'>
Index: 1850 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          1850 non-null   str
 1   customer_id       1847 non-null   str
 2   product_id        1847 non-null   str
 3   order_date        1850 non-null   datetime64[us]
 4   ship_date         1709 non-null   datetime64[us]
 5   quantity          1850 non-null   int64
 6   unit_price        1850 non-null   str
 7   discount_percent  1613 non-null   float64
 8   shipping_cost     1764 non-null   float64
 9   total_amount      1850 non-null   float64
 10  payment_method    1804 non-null   str
 11  order_status      1850 non-null   str
 12  region            1500 non-null   str
 13  sales_channel     1850 non-null   str
 14  return_flag       1663 non-null   str
dtypes: datetime64[us](2), float64(3), int64(1), str(9)
memory usage: 343.7 KB

In [188]:
kp[kp["ship_date"].isnull()]

,order_id,customer_id,product_id,order_date,ship_date,quantity,unit_price,discount_percent,shipping_cost,total_amount,payment_method,order_status,region,sales_channel,return_flag
8,ORD01418,CUST0135,PROD0094,2024-05-06,NaT,1,5579.66,10.0,63.82,5085.51,Upi,Returned,South,Online,Yes
24,ORD00003,CUST0099,PROD0031,2024-04-02,NaT,2,15661.2,15.0,75.49,26699.53,Credit Card,Returned,North,In-Store,No
26,ORD01505,CUST0080,PROD0064,2023-12-26,NaT,-1,13808.45,0.0,224.31,14032.76,Upi,Delivered,NaN,Online,No
27,ORD00111,CUST0121,PROD0064,2023-06-19,NaT,5,13808.45,15.0,60.22,58746.13,Debit Card,Delivered,West,Online,No
31,ORD00501,CUST0005,PROD0083,2024-12-08,NaT,5,17414.05,10.0,32.76,78395.99,Credit Card,Delivered,West,Online,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1915,ORD00924,CUST0041,PROD0088,2024-08-10,NaT,1,16043.08,5.0,NaN,15416.23,Upi,Returned,NaN,Mobile App,No
1921,ORD00482,CUST0051,PROD0010,2024-11-14,NaT,1,9930.05,15.0,166.02,8606.56,Upi,Delivered,East,Mobile App,Yes
1922,ORD00932,CUST0032,PROD0033,2023-02-08,NaT,2,14138.95,5.0,135.97,26999.98,Cod,In-Transit,North,In-Store,No
1975,ORD01537,CUST0031,PROD0063,2024-07-17,NaT,3,6598.24,15.0,219.21,17044.72,Credit Card,Delivered,NaN,Online,No
1998,ORD01221,CUST0156,PROD0090,2024-01-11,NaT,4,12088.33,0.0,NaN,48561.19,Upi,Delivered,NaN,Mobile App,No

In [189]:
kp.dropna(subset="customer_id",inplace=True )

In [190]:
kp[kp['ship_date'].isna()]['order_status'].value_counts()

order_status
Delivered     42
Returned      24
Shipped       21
Processing    20
Cancelled     19
In-Transit    15
Name: count, dtype: int64

In [191]:
kp["ship_date"]=kp["ship_date"].fillna(kp["order_date"]+pd.Timedelta(days=5))

In [192]:
kp.isnull().sum()

order_id              0
customer_id           0
product_id            0
order_date            0
ship_date             0
quantity              0
unit_price            0
discount_percent    237
shipping_cost        86
total_amount          0
payment_method       46
order_status          0
region              350
sales_channel         0
return_flag         186
dtype: int64

In [193]:
kp["discount_percent"]=kp["discount_percent"].fillna(kp["discount_percent"].median())

In [194]:
(kp["quantity"]<0).sum() #count -ve qty

np.int64(217)

In [195]:
kp[kp["quantity"]<0] #see -ve qty rows

,order_id,customer_id,product_id,order_date,ship_date,quantity,unit_price,discount_percent,shipping_cost,total_amount,payment_method,order_status,region,sales_channel,return_flag
15,ORD01303,CUST0053,PROD0058,2024-06-22,2024-06-30,-1,9834.07,5.0,14.45,9848.52,Credit Card,In-Transit,West,Mobile App,NaN
25,ORD01076,CUST0078,PROD0057,2023-01-19,2023-01-21,-1,12771.68,5.0,NaN,12898.82,Upi,Processing,East,In-Store,Yes
26,ORD01505,CUST0080,PROD0064,2023-12-26,2023-12-31,-1,13808.45,0.0,224.31,14032.76,Upi,Delivered,NaN,Online,No
41,ORD00721,CUST0128,PROD0039,2024-05-15,2024-05-20,-1,15091.15,5.0,57.03,14393.62,Upi,Returned,West,Online,No
46,ORD01261,CUST0156,PROD0014,2024-09-29,2024-10-01,-1,17479.16,20.0,31.28,14014.61,Upi,Cancelled,NaN,In-Store,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1967,ORD01728,CUST0039,PROD0021,2024-10-12,2024-12-18,-1,6518.87,0.0,240.00,6758.87,Cod,Cancelled,South,In-Store,No
1969,ORD01469,CUST0143,PROD0068,2023-09-02,2023-11-02,-1,3558.79,15.0,212.55,3237.52,Upi,Shipped,South,Online,No
1980,ORD01093,CUST0149,PROD0022,2023-07-01,2023-01-15,-1,21812.68,0.0,214.08,22026.76,Upi,Delivered,West,In-Store,Yes
1982,ORD00905,CUST0097,PROD0095,2023-09-01,2023-01-08,-1,14966.39,5.0,NaN,14321.91,Net Banking,Cancelled,NaN,Mobile App,No
1999,ORD00176,CUST0154,PROD0071,2023-06-14,2023-06-13,-1,₹1509.25,0.0,112.35,1621.60,Credit Card,Delivered,NaN,Mobile App,No

In [196]:
kp["quantity"]=kp["quantity"].abs() # convert -ve to +ve

In [197]:
kp[kp["shipping_cost"].isnull()]

,order_id,customer_id,product_id,order_date,ship_date,quantity,unit_price,discount_percent,shipping_cost,total_amount,payment_method,order_status,region,sales_channel,return_flag
25,ORD01076,CUST0078,PROD0057,2023-01-19,2023-01-21,1,12771.68,5.0,NaN,12898.82,Upi,Processing,East,In-Store,Yes
105,ORD00971,CUST0041,PROD0073,2023-08-04,2023-04-08,1,10432.09,0.0,NaN,10610.01,Credit Card,Shipped,East,Online,No
107,ORD01151,CUST0117,PROD0034,2023-01-25,2023-01-31,2,11290.33,5.0,NaN,22785.88,COD,Delivered,South,Online,No
115,ORD01785,CUST0028,PROD0096,2024-11-28,2024-01-12,1,1277.29,0.0,NaN,1472.63,Debit Card,Delivered,West,Mobile App,No
119,ORD00722,CUST0189,PROD0097,2024-01-30,2024-03-02,1,18995.32,0.0,NaN,19192.39,Cod,Delivered,East,In-Store,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1915,ORD00924,CUST0041,PROD0088,2024-08-10,2024-08-15,1,16043.08,5.0,NaN,15416.23,Upi,Returned,NaN,Mobile App,No
1926,ORD00760,CUST0035,PROD0096,2024-12-19,2024-12-23,1,1277.29,15.0,NaN,1100.70,Credit Card,Cancelled,West,Online,No
1945,ORD00945,CUST0158,PROD0006,2024-03-22,2024-03-22,2,6650.61,20.0,NaN,10760.86,Credit Card,Shipped,South,In-Store,Yes
1982,ORD00905,CUST0097,PROD0095,2023-09-01,2023-01-08,1,14966.39,5.0,NaN,14321.91,Net Banking,Cancelled,NaN,Mobile App,No
1998,ORD01221,CUST0156,PROD0090,2024-01-11,2024-01-16,4,12088.33,0.0,NaN,48561.19,Upi,Delivered,NaN,Mobile App,No

In [198]:
kp["shipping_cost"]=kp["shipping_cost"].fillna(kp["shipping_cost"].median())

In [199]:
kp.isnull().sum()

order_id              0
customer_id           0
product_id            0
order_date            0
ship_date             0
quantity              0
unit_price            0
discount_percent      0
shipping_cost         0
total_amount          0
payment_method       46
order_status          0
region              350
sales_channel         0
return_flag         186
dtype: int64

In [200]:
kp["payment_method"]=kp["payment_method"].replace("Cod","COD")

In [201]:
kp["payment_method"].unique()

<ArrowStringArray>
['COD', 'Net Banking', 'Debit Card', 'Upi', 'Credit Card', nan]
Length: 6, dtype: str

In [202]:
kp["payment_method"]=kp["payment_method"].fillna(kp["payment_method"].mode()[0])

In [203]:
kp["payment_method"].isnull().sum()

np.int64(0)

In [13]:
import numpy as np

kp.loc[kp['region'].isna(), 'region'] = np.random.choice(
    kp['region'].dropna(),
    size=kp['region'].isna().sum()
)

In [14]:
kp.isnull().sum()

order_id               0
customer_id            0
product_id             0
order_date             0
ship_date              0
quantity               0
unit_price             0
discount_percent       0
shipping_cost          0
total_amount           0
payment_method         0
order_status           0
region                 0
sales_channel          0
return_flag            0
Gross_amount           0
net_amount             0
loss_amount            0
cost_price             0
total_cost             0
profit                 0
profit_margin_pct    283
dtype: int64

In [206]:
import numpy as np

kp.loc[kp['return_flag'].isna(), 'return_flag'] = np.random.choice(
    kp['return_flag'].dropna(),
    size=kp['return_flag'].isna().sum()
)

In [207]:
kp

,order_id,customer_id,product_id,order_date,ship_date,quantity,unit_price,discount_percent,shipping_cost,total_amount,payment_method,order_status,region,sales_channel,return_flag
0,ORD01073,CUST0013,PROD0086,2023-03-17,2023-03-22,1,1008.99,5.0,72.84,1081.83,COD,Processing,North,Mobile App,No
1,ORD01049,CUST0060,PROD0016,2023-05-29,2023-05-27,1,9295.74,0.0,146.52,9442.26,COD,Processing,West,Mobile App,No
2,ORD00205,CUST0128,PROD0070,2023-06-01,2023-01-13,5,2262.55,5.0,54.22,10801.33,Net Banking,Shipped,West,Mobile App,No
3,ORD00695,CUST0190,PROD0033,2024-11-28,2024-07-12,4,14138.95,10.0,134.07,51034.29,Debit Card,Delivered,South,Online,No
4,ORD01759,CUST0100,PROD0018,2024-03-13,2024-03-19,3,21702.52,0.0,117.80,65225.36,Net Banking,Returned,West,In-Store,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,ORD01604,CUST0087,PROD0035,2024-11-27,2024-11-25,2,13720.55,0.0,152.21,27593.31,Upi,Cancelled,South,Mobile App,No
1996,ORD00503,CUST0058,PROD0007,2023-11-01,2023-11-01,1,2136.66,15.0,215.35,2031.51,Net Banking,Delivered,North,Mobile App,Yes
1997,ORD00538,CUST0021,PROD0071,2024-05-05,2024-05-05,2,1509.25,0.0,26.02,3044.52,Debit Card,Delivered,North,Online,No
1998,ORD01221,CUST0156,PROD0090,2024-01-11,2024-01-16,4,12088.33,0.0,119.49,48561.19,Upi,Delivered,West,Mobile App,No
1999,ORD00176,CUST0154,PROD0071,2023-06-14,2023-06-13,1,₹1509.25,0.0,112.35,1621.60,Credit Card,Delivered,West,Mobile App,No

In [208]:
Cancelled_returned=kp["order_status"].isin(['Cancelled', 'Returned'])

In [209]:
kp["Gross_amount"]=kp["total_amount"]

In [210]:
kp["net_amount"]=kp["total_amount"].where(~Cancelled_returned,0)

In [211]:
kp["loss_amount"]=kp["total_amount"].where(Cancelled_returned,0)
kp

,order_id,customer_id,product_id,order_date,ship_date,quantity,unit_price,discount_percent,shipping_cost,total_amount,payment_method,order_status,region,sales_channel,return_flag,Gross_amount,net_amount,loss_amount
0,ORD01073,CUST0013,PROD0086,2023-03-17,2023-03-22,1,1008.99,5.0,72.84,1081.83,COD,Processing,North,Mobile App,No,1081.83,1081.83,0.00
1,ORD01049,CUST0060,PROD0016,2023-05-29,2023-05-27,1,9295.74,0.0,146.52,9442.26,COD,Processing,West,Mobile App,No,9442.26,9442.26,0.00
2,ORD00205,CUST0128,PROD0070,2023-06-01,2023-01-13,5,2262.55,5.0,54.22,10801.33,Net Banking,Shipped,West,Mobile App,No,10801.33,10801.33,0.00
3,ORD00695,CUST0190,PROD0033,2024-11-28,2024-07-12,4,14138.95,10.0,134.07,51034.29,Debit Card,Delivered,South,Online,No,51034.29,51034.29,0.00
4,ORD01759,CUST0100,PROD0018,2024-03-13,2024-03-19,3,21702.52,0.0,117.80,65225.36,Net Banking,Returned,West,In-Store,No,65225.36,0.00,65225.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,ORD01604,CUST0087,PROD0035,2024-11-27,2024-11-25,2,13720.55,0.0,152.21,27593.31,Upi,Cancelled,South,Mobile App,No,27593.31,0.00,27593.31
1996,ORD00503,CUST0058,PROD0007,2023-11-01,2023-11-01,1,2136.66,15.0,215.35,2031.51,Net Banking,Delivered,North,Mobile App,Yes,2031.51,2031.51,0.00
1997,ORD00538,CUST0021,PROD0071,2024-05-05,2024-05-05,2,1509.25,0.0,26.02,3044.52,Debit Card,Delivered,North,Online,No,3044.52,3044.52,0.00
1998,ORD01221,CUST0156,PROD0090,2024-01-11,2024-01-16,4,12088.33,0.0,119.49,48561.19,Upi,Delivered,West,Mobile App,No,48561.19,48561.19,0.00
1999,ORD00176,CUST0154,PROD0071,2023-06-14,2023-06-13,1,₹1509.25,0.0,112.35,1621.60,Credit Card,Delivered,West,Mobile App,No,1621.60,1621.60,0.00

In [212]:
kp=kp.merge(
    kp_product[["product_id","cost_price"]],
    on='product_id',how='left'
)

In [213]:
kp["total_cost"]=kp["quantity"]*kp["cost_price"]

In [214]:
kp["profit"]=kp["net_amount"]-kp["total_cost"]

In [215]:
kp[kp["profit"]<0]

,order_id,customer_id,product_id,order_date,ship_date,quantity,unit_price,discount_percent,shipping_cost,total_amount,...,order_status,region,sales_channel,return_flag,Gross_amount,net_amount,loss_amount,cost_price,total_cost,profit
4,ORD01759,CUST0100,PROD0018,2024-03-13,2024-03-19,3,21702.52,0.0,117.80,65225.36,...,Returned,West,In-Store,No,65225.36,0.0,65225.36,12543.29,37629.87,-37629.87
6,ORD01203,CUST0047,PROD0070,2023-03-31,2023-03-31,1,2262.55,20.0,55.55,1865.59,...,Cancelled,West,Online,No,1865.59,0.0,1865.59,1682.14,1682.14,-1682.14
8,ORD01418,CUST0135,PROD0094,2024-05-06,2024-05-11,1,5579.66,10.0,63.82,5085.51,...,Returned,South,Online,Yes,5085.51,0.0,5085.51,3288.40,3288.40,-3288.40
10,ORD00869,CUST0144,PROD0097,2023-01-18,2023-01-20,1,18995.32,15.0,240.01,16386.03,...,Cancelled,North,Mobile App,No,16386.03,0.0,16386.03,14670.87,14670.87,-14670.87
11,ORD01338,CUST0192,PROD0004,2024-11-08,2024-08-20,4,10787.53,0.0,29.14,43179.26,...,Cancelled,East,Online,No,43179.26,0.0,43179.26,7012.90,28051.60,-28051.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1829,ORD01192,CUST0012,PROD0058,2024-02-03,2024-06-03,2,9834.07,0.0,2.57,19670.71,...,Cancelled,West,Mobile App,No,19670.71,0.0,19670.71,6032.58,12065.16,-12065.16
1830,ORD00905,CUST0097,PROD0095,2023-09-01,2023-01-08,1,14966.39,5.0,119.49,14321.91,...,Cancelled,East,Mobile App,No,14321.91,0.0,14321.91,11139.28,11139.28,-11139.28
1833,ORD00367,CUST0121,PROD0040,2024-09-09,2024-12-09,2,18476.06,15.0,242.57,31651.87,...,Cancelled,South,In-Store,No,31651.87,0.0,31651.87,13298.28,26596.56,-26596.56
1839,ORD01640,CUST0072,PROD0053,2023-09-09,2023-07-09,4,3950.23,0.0,186.25,15987.17,...,Cancelled,West,Mobile App,No,15987.17,0.0,15987.17,3082.66,12330.64,-12330.64
1842,ORD01604,CUST0087,PROD0035,2024-11-27,2024-11-25,2,13720.55,0.0,152.21,27593.31,...,Cancelled,South,Mobile App,No,27593.31,0.0,27593.31,8206.82,16413.64,-16413.64

In [216]:
kp = kp.drop(columns=['profit', 'total_cost'])

In [217]:
def calc_cost(row):
    if row['order_status'] == 'Cancelled':
        return 0
    elif row['order_status'] == 'Returned':
        return row['shipping_cost']
    else:
        return row['quantity'] * row['cost_price']

kp['total_cost'] = kp.apply(calc_cost, axis=1)

In [222]:
kp["profit"]=kp["net_amount"]-kp["total_cost"]

In [227]:
kp

,order_id,customer_id,product_id,order_date,ship_date,quantity,unit_price,discount_percent,shipping_cost,total_amount,...,order_status,region,sales_channel,return_flag,Gross_amount,net_amount,loss_amount,cost_price,total_cost,profit
0,ORD01073,CUST0013,PROD0086,2023-03-17,2023-03-22,1,1008.99,5.0,72.84,1081.83,...,Processing,North,Mobile App,No,1081.83,1081.83,0.00,570.40,570.40,511.43
1,ORD01049,CUST0060,PROD0016,2023-05-29,2023-05-27,1,9295.74,0.0,146.52,9442.26,...,Processing,West,Mobile App,No,9442.26,9442.26,0.00,7676.48,7676.48,1765.78
2,ORD00205,CUST0128,PROD0070,2023-06-01,2023-01-13,5,2262.55,5.0,54.22,10801.33,...,Shipped,West,Mobile App,No,10801.33,10801.33,0.00,1682.14,8410.70,2390.63
3,ORD00695,CUST0190,PROD0033,2024-11-28,2024-07-12,4,14138.95,10.0,134.07,51034.29,...,Delivered,South,Online,No,51034.29,51034.29,0.00,8668.21,34672.84,16361.45
4,ORD01759,CUST0100,PROD0018,2024-03-13,2024-03-19,3,21702.52,0.0,117.80,65225.36,...,Returned,West,In-Store,No,65225.36,0.00,65225.36,12543.29,117.80,-117.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1842,ORD01604,CUST0087,PROD0035,2024-11-27,2024-11-25,2,13720.55,0.0,152.21,27593.31,...,Cancelled,South,Mobile App,No,27593.31,0.00,27593.31,8206.82,0.00,0.00
1843,ORD00503,CUST0058,PROD0007,2023-11-01,2023-11-01,1,2136.66,15.0,215.35,2031.51,...,Delivered,North,Mobile App,Yes,2031.51,2031.51,0.00,1243.29,1243.29,788.22
1844,ORD00538,CUST0021,PROD0071,2024-05-05,2024-05-05,2,1509.25,0.0,26.02,3044.52,...,Delivered,North,Online,No,3044.52,3044.52,0.00,854.02,1708.04,1336.48
1845,ORD01221,CUST0156,PROD0090,2024-01-11,2024-01-16,4,12088.33,0.0,119.49,48561.19,...,Delivered,West,Mobile App,No,48561.19,48561.19,0.00,9190.14,36760.56,11800.63
1846,ORD00176,CUST0154,PROD0071,2023-06-14,2023-06-13,1,₹1509.25,0.0,112.35,1621.60,...,Delivered,West,Mobile App,No,1621.60,1621.60,0.00,854.02,854.02,767.58

In [233]:
kp['profit_margin_pct'] = (kp['profit'] / kp['net_amount'] * 100).round(2)

In [236]:
kp['profit_margin_pct'] = kp['profit_margin_pct'].replace([np.inf, -np.inf], np.nan)

In [16]:
kp.to_csv("C:/Users/Kailash J Choudhary/Downloads/orders_cleaned2.csv",index=False)

In [ ]:
kp["unit_price"] = (
    kp["unit_price"]
    .astype(str)
    .str.replace("â‚¹", "", regex=False)
    .str.replace("₹", "", regex=False)
    .str.split(".").str[0]
    .astype(int)
)

In [15]:
kp.isnull().sum()

order_id               0
customer_id            0
product_id             0
order_date             0
ship_date              0
quantity               0
unit_price             0
discount_percent       0
shipping_cost          0
total_amount           0
payment_method         0
order_status           0
region                 0
sales_channel          0
return_flag            0
Gross_amount           0
net_amount             0
loss_amount            0
cost_price             0
total_cost             0
profit                 0
profit_margin_pct    283
dtype: int64